steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/spxgc', '.']
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/spxgc:latest'