steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/spxgc', '.']
- name: "gcr.io/cloud-builders/gke-deploy"
  args: ['run', '--filename=/kubernetes', '--image=us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/spxgc:latest', '--location=us-central1', '--cluster=spx-gc-demo-cluster']
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/spxgc:latest'