apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spx-gc-demo-backend
spec:
  selector:
    matchLabels:
      app: spx-gc-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: spx-gc-demo
    spec:
      containers:
      - name: spx-gc-demo-container
        imagePullPolicy: Always
        image: _IMAGE
        ports:
        - containerPort: 5656
        volumeMounts:
        - name: spx-gc-demo-logs
          mountPath: /usr/src/app/LOGS
        - name: spx-gc-demo-assets
          mountPath: /usr/src/app/ASSETS
        - name: spx-gc-demo-dataroot
          mountPath: /usr/src/app/DATAROOT
  volumeClaimTemplates:
  - metadata:
      name: spx-gc-demo-logs
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 100M
  - metadata:
      name: spx-gc-demo-assets
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 100M
  - metadata:
      name: spx-gc-demo-dataroot
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 100M